# Generated by Django 3.2.5 on 2021-07-18 19:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfoBasic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('name', models.CharField(max_length=150)),
                ('age', models.IntegerField(default=18)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('branch', models.CharField(choices=[('CS', 'Computer Science'), ('EC', 'Electrical'), ('ME', 'Mechanical'), ('EX', 'Electronics')], max_length=50)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Alumni.batch')),
            ],
        ),
    ]
