# Generated by Django 3.2.5 on 2021-07-18 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfobasic',
            name='age',
            field=models.IntegerField(blank=True, default=18, null=True),
        ),
        migrations.AlterField(
            model_name='userinfobasic',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Alumni.batch'),
        ),
        migrations.AlterField(
            model_name='userinfobasic',
            name='branch',
            field=models.CharField(blank=True, choices=[('CS', 'Computer Science'), ('EC', 'Electrical'), ('ME', 'Mechanical'), ('EX', 'Electronics')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='userinfobasic',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
