# Generated by Django 3.2.5 on 2021-07-18 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0002_auto_20210719_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfobasic',
            name='age',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
