# Generated by Django 3.2.5 on 2021-07-27 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0003_alter_userinfobasic_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('enroll_no', models.CharField(blank=True, max_length=150, null=True)),
                ('mobile', models.IntegerField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
            ],
        ),
    ]
