# Generated by Django 3.2.5 on 2021-07-28 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0005_auto_20210728_0328'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLinkInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('school', models.CharField(blank=True, max_length=150, null=True)),
                ('fav_part_of_college', models.CharField(blank=True, choices=[('Canteen', 'Canteen'), ('Tapri', 'Nanu Kirana'), ('Terrace stairs', 'Terrace Stairs'), ('Hostel', 'Hostel')], max_length=50, null=True)),
                ('fav_food_of_canteen', models.CharField(blank=True, choices=[('Samosa', 'Samosa'), ('Chai', 'Chai'), ('Fried Rice', 'Fried Rice'), ('Tanhai', 'Tanhai')], max_length=50, null=True)),
                ('insta', models.CharField(blank=True, max_length=1000, null=True)),
                ('blog_link', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='userinfobasic',
            name='branch',
            field=models.CharField(blank=True, choices=[('Computer Science', 'Computer Science'), ('Electrical', 'Electrical'), ('Mechanical', 'Mechanical'), ('Electronics', 'Electronics')], max_length=50, null=True),
        ),
    ]
