# Generated by Django 3.2.5 on 2021-09-07 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0007_thoughtsbyuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('started_from', models.DateTimeField(default=datetime.datetime(2021, 9, 7, 21, 35, 10, 921839))),
                ('ended_on', models.DateTimeField(default=datetime.datetime(2021, 9, 7, 21, 35, 10, 921839))),
                ('role', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=150)),
                ('learnt_from', models.CharField(max_length=150)),
                ('level', models.CharField(choices=[('Basic', 'Basic'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced'), ('Elite', 'Elite')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='thoughtsbyuser',
            name='posted_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 7, 21, 35, 10, 919847)),
        ),
    ]
