# Generated by Django 3.2.5 on 2021-09-07 16:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0008_auto_20210907_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='user',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='skills',
            name='user',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='ended_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 7, 22, 4, 35, 485787)),
        ),
        migrations.AlterField(
            model_name='job',
            name='started_from',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 7, 22, 4, 35, 485787)),
        ),
        migrations.AlterField(
            model_name='thoughtsbyuser',
            name='posted_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 7, 22, 4, 35, 483785)),
        ),
    ]
