# Generated by Django 3.2.5 on 2021-09-08 10:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0009_auto_20210907_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='position',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='type',
            field=models.CharField(choices=[('Internship', 'Internship'), ('Job', 'Job')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='ended_on',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='job',
            name='started_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='thoughtsbyuser',
            name='posted_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 8, 16, 11, 23, 810183)),
        ),
    ]
