# Generated by Django 3.2.5 on 2021-09-08 11:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0013_auto_20210908_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thoughtsbyuser',
            name='posted_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 8, 16, 47, 59, 285567)),
        ),
    ]
