# Generated by Django 3.2.5 on 2021-09-08 11:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0015_alter_thoughtsbyuser_posted_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='ended_on',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='thoughtsbyuser',
            name='posted_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 8, 16, 51, 53, 937021)),
        ),
    ]
