# Generated by Django 3.2.5 on 2021-09-16 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0016_auto_20210908_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thoughtsbyuser',
            name='posted_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 17, 2, 23, 46, 94325)),
        ),
    ]
