# Generated by Django 3.2.5 on 2021-09-18 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Alumni', '0018_auto_20210917_0225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insights',
            old_name='user',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='insights',
            name='posted_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 19, 0, 46, 52, 525542)),
        ),
        migrations.AlterField(
            model_name='thoughtsbyuser',
            name='posted_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 19, 0, 46, 52, 520553)),
        ),
    ]
